export const GET_RULES = 'GET_RULES';
export const SET_VISIBILITY_BUTTON = 'SET_VISIBILITY_BUTTON';
export const SET_VIBISILITY_MODAL = 'SET_VISIBILITY_MODAL';
export const GET_QUESTION_FETCH = 'GET_QUESTION_FETCH';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_ERROR = 'GET_QUESTION_ERROR';
