export const GET_RULES_FETCH = 'GET_RULES_FETCH';
export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
export const GET_RULES_ERROR = 'GET_RULES_ERROR';

export const GET_QUESTION_FETCH = 'GET_QUESTION_FETCH';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_ERROR = 'GET_QUESTION_ERROR';

export const GET_ROOM_FETCH = 'GET_ROOM_FETCH';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_ERROR = 'GET_ROOM_ERROR';

export const POST_START_GAME_FETCH = 'POST_START_GAME_FETCH';
export const POST_START_GAME_SUCCESS = 'POST_START_GAME_SUCCESS';
export const POST_START_GAME_ERROR = 'POST_START_GAME_ERROR';

export const GAME_ANSWER_QUESTION_FETCH = 'GAME_ANSWER_QUESTION_FETCH';
export const GAME_ANSWER_QUESTION_SUCCESS = 'GAME_ANSWER_QUESTION_SUCCESS';
export const GAME_ANSWER_QUESTION_ERROR = 'GAME_ANSWER_QUESTION_ERROR';

export const SET_VISIBILITY_BUTTON = 'SET_VISIBILITY_BUTTON';
export const SET_VIBISILITY_MODAL = 'SET_VISIBILITY_MODAL';
